version: '3.8'

services:
  # Bot service
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kasper-bot
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./transcripts:/app/transcripts
    environment:
      - TOKEN=${TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/kasper?schema=public
    networks:
      - kasper-network

  # Database service
  db:
    image: postgres:14-alpine
    container_name: kasper-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=kasper
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - kasper-network

volumes:
  postgres-data:
    name: kasper-postgres-data

networks:
  kasper-network:
    name: kasper-network 